services:
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: local-kafka
    ports:
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      CLUSTER_ID: "q1Sh-9K9R4yA2n6n6yXxGw"

      KAFKA_LISTENERS: >
        PLAINTEXT://0.0.0.0:29092,
        CONTROLLER://0.0.0.0:29093

      KAFKA_ADVERTISED_LISTENERS: >
        PLAINTEXT://localhost:29092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        PLAINTEXT:PLAINTEXT,
        CONTROLLER:PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs

      KAFKA_HEAP_OPTS: "-Xms256m -Xmx256m"

    mem_limit: 512m
